name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Set up Ruby # rubocop
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0
        
    - name: Set up tools
      run: sudo apt-get install jq

    - name: Set up gems
      run: cd example && bundle install

    - name: Build
      run: make build

    - name: Test
      run: go test -v ./...
      
    - name: Integration test
      run: cd example && ./test.sh ../target/check_diff
