name: Go

on:
  push:
    branches: [ main ]
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Set up Ruby # rubocop
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0

    - name: Set up gems
      run: cd integration_tests && bundle install

    - name: Build
      run: make build

    - name: Set up testenv
      run: |
        go install github.com/golang/mock/mockgen
        make mockgen

    - name: Test
      run: go test -v -covermode atomic -coverprofile=covprofile ./...
    - name: Install goveralls
      run: go install github.com/mattn/goveralls@latest
    - name: Send coverage
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: goveralls -coverprofile=covprofile -service=github